OLED_ENABLE = yes		

CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = yes

PS2_MOUSE_ENABLE = yes	
PS2_ENABLE = yes


VIA_ENABLE  = yes    # Enable VIA
VIAL_ENABLE = yes    # Enable VIAL
VIAL_INSECURE = yes 


NKRO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no



# reducing firmware

QMK_SETTINGS = no
LTO_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
KEY_LOCK_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
